### ISSUE TITLE
Custom UI for login

### ISSUE THREAD

**Issue by jakunico** [sonsongithub/reddift#186]
Hi there,

I was wondering wether there's a way you can skip OAUTH authentication method and do a regular POST of your username/password like [other clients do](https://github.com/samsymons/RedditKit/blob/master/Classes/Networking/RKClient.m).

The mains reason why I'm wondering this is because you'd be able to build a custom UI for login which is much better than the ugly web login interface.

Well, let me know what you think @sonsongithub !

**Comment by sonsongithub** [comment]
reddit.com announced that cookie-authentication will be discontinued in the future.
Cookie-authentication is currently deprecating.

I do not want to implement the login method which is will be discontinued....
I put up with the OAuth in order to make applications more secure.

https://www.reddit.com/r/redditdev/comments/2ujhkr/important_api_licensing_terms_clarified/

**Comment by jakunico** [comment]
I see... There're some apps still using this method and still working correctly.

Anyway, that makes sense

**Comment by sonsongithub** [comment]
Thank you for your question!
